name: YuriBucci-Solfacil/slack-approval
description: Custom action to send approval request to Slack from Github, allowing only specified approvers
author: Pranava S Balugari
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: check-circle
  color: orange

inputs:
  baseMessageTs:
    description: "Target message timestamp to update. If not provided, a new message will be posted"
    required: false
    default: ""
  approvers:
    description: "A comma-separated list of approvers' Slack user IDs or email addresses. When using email addresses, the Slack app needs users:read.email scope."
    required: true
  minimumApprovalCount:
    description: "The minimum number of approvals required"
    required: false
    default: "1"
  baseMessagePayload:
    description: "The base message payload to display. If not set, will use default message from README. To customize, provide Slack message payload JSON"
    required: false
    default: |
      {
        "blocks": [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "🔔 Approval Request",
              "emoji": true
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*GitHub Actions Workflow* requires your approval to proceed."
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "context",
            "elements": [
              {
                "type": "mrkdwn",
                "text": "Approval request from GitHub Actions"
              }
            ]
          }
        ]
      }
  successMessagePayload:
    description: "The message body indicating approval is success. If not set, will use baseMessagePayload."
    required: false
    default: |
      {
        "blocks": [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "✅ Approval Completed",
              "emoji": true
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "The workflow has been *successfully approved* and will continue execution."
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "context",
            "elements": [
              {
                "type": "mrkdwn",
                "text": "Approved via GitHub Actions workflow"
              }
            ]
          }
        ]
      }
  failMessagePayload:
    description: "The message body indicating approval is fail. If not set, will use baseMessagePayload."
    required: false
    default: |
      {
        "blocks": [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "❌ Approval Rejected",
              "emoji": true
            }
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "The workflow has been *rejected* and will not continue execution."
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "context",
            "elements": [
              {
                "type": "mrkdwn",
                "text": "Rejected via GitHub Actions workflow"
              }
            ]
          }
        ]
      }
  approveButtonText:
    description: "Custom text for the approve button. Default is '✅ Approve'"
    required: false
    default: "✅ Approve"
  rejectButtonText:
    description: "Custom text for the reject button. Default is '❌ Reject'"
    required: false
    default: "❌ Reject"
  debug:
    description: "Enable debug logging (verbose output)"
    required: false
    default: "false"

outputs:
  mainMessageTs:
    description: "Slack main message timestamp"
# Environment variables required:
# SLACK_BOT_TOKEN - Slack bot token for authentication
# SLACK_SIGNING_SECRET - Slack app signing secret
# SLACK_APP_TOKEN - Slack app token for socket mode
# SLACK_CHANNEL_ID - Target Slack channel ID (Optional when using direct messages, used as fallback when direct messages fail)
# SLACK_USER_ID - Target Slack user ID for direct message 
# SLACK_USER_EMAIL - Target Slack user email (will be converted to user ID automatically)
# NOTE: For SLACK_USER_EMAIL functionality, your Slack app needs users:read.email and im:write scopes
# UNIQUE_STEP_ID - Unique identifier for this approval step (Optional, will be auto-generated if not provided)

