name: YuriBucci-Solfacil/slack-approval
description: Custom action to send approval request to Slack from Github, allowing only specified approvers
author: Pranava S Balugari
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: check-circle
  color: orange

inputs:
  baseMessageTs:
    description: "Target message timestamp to update. If not provided, a new message will be posted"
    required: false
    default: ""
  approvers:
    description: "A comma-separated list of approvers' Slack user IDs or email addresses. When using email addresses, the Slack app needs users:read.email scope."
    required: true
  minimumApprovalCount:
    description: "The minimum number of approvals required"
    required: false
    default: "1"
  baseMessagePayload:
    description: "The base message payload to display. If not set, will use default message from README. To customize, provide Slack message payload JSON"
    required: false
    default: |
      {}
  successMessagePayload:
    description: "The message body indicating approval is success. If not set, will use baseMessagePayload."
    required: false
    default: |
      {}
  failMessagePayload:
    description: "The message body indicating approval is fail. If not set, will use baseMessagePayload."
    required: false
    default: |
      {}

outputs:
  mainMessageTs:
    description: "Slack main message timestamp"
# Environment variables required:
# SLACK_BOT_TOKEN - Slack bot token for authentication
# SLACK_SIGNING_SECRET - Slack app signing secret
# SLACK_APP_TOKEN - Slack app token for socket mode
# SLACK_CHANNEL_ID - Target Slack channel ID (Optional when using direct messages, used as fallback when direct messages fail)
# SLACK_USER_ID - Target Slack user ID for direct message 
# SLACK_USER_EMAIL - Target Slack user email (will be converted to user ID automatically)
# NOTE: For SLACK_USER_EMAIL functionality, your Slack app needs users:read.email and im:write scopes
# UNIQUE_STEP_ID - Unique identifier for this approval step

